spring.application.name=learnAuth
spring.config.import=optional:file:.env[.properties]

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/learnAuth
spring.datasource.username=postgres
spring.datasource.password=Thanhkon123@

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt_secret=${JWT_SECRET}